### PR TITLE
Change wirebox calls to use entity service

### PR DESCRIPTION
**Pull request by jclausen**
This seems to prevent the intermittent mapping/scanning errors that appear from incorrect mapping references between Hibernate and Wirebox.

### CODE REVIEW

**Review by elpete — APPROVED** [review]

**Comment by elpete** [comment]
Can you test ACF11 locally?  It's failing on Travis for some reason.

**Review by elpete — CHANGES_REQUESTED** [review]
Please test on ACF11. Tests are failing on Travis

**Comment by jclausen** [comment]
Requested changes have been made and the build process fixed

**Review by elpete — APPROVED** [review]

**Comment by elpete** [comment]
Thanks for fixing the build process, @jclausen!

**Pull request merged**
